package com.horizon.horizify.utils

enum class BibleVersion {
    ANG_BAGONG_BIBLIA,
    ANG_DATING_BIBLIA,
    THE_AMPLIFIED_BIBLE,
    CONTEMPORARY_ENGLISH_VERSION,
    ENGLISH_STANDARD_VERSION,
    KING_JAMES_VERSION,
    MODERN_KING_JAMES_VERSION,
    THE_MESSAGE,
    NEW_AMERICAN_STANDARD_BIBLE,
    NEW_INTERNATIONAL_VERSION,
    NEW_KING_JAMES_VERSION,
    REVISED_STANDARD_VERSION
}